# Generated by Django 4.2.5 on 2024-03-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_unit", models.CharField(max_length=50)),
                ("minor_unit", models.CharField(max_length=30)),
                ("major_to_minor", models.SmallIntegerField()),
                ("ISO", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="identifier_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="industry_sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="instrument_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_type", models.CharField(max_length=25)),
                ("instrument_class", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="organization_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="industry_subsector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsector_name", models.CharField(max_length=255, unique=True)),
                (
                    "sector_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classifiers.industry_sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("short_name", models.CharField(max_length=20)),
                ("ISO2", models.CharField(max_length=2, unique=True)),
                ("ISO3", models.CharField(max_length=3, unique=True)),
                (
                    "ccy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.currency",
                    ),
                ),
            ],
        ),
    ]
