# Generated by Django 4.2.5 on 2024-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
