# Generated by Django 4.2.5 on 2024-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="market_data_source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
