# Generated by Django 4.2.5 on 2024-05-05 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0002_accounting_method_acrrual_type_asset_flow_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="acrrual_type",
            new_name="accrual_type",
        ),
    ]
