# Generated by Django 4.2.5 on 2024-08-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_cash_position_position_type_and_more'),
        ('classifiers', '0002_country_active_currency_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='position_type',
        ),
    ]
