# Generated by Django 4.2.5 on 2024-04-12 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0002_market_data_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="ccy_id",
            new_name="ccy",
        ),
        migrations.RenameField(
            model_name="industry_subsector",
            old_name="sector_id",
            new_name="sector",
        ),
    ]
