# Generated by Django 4.2.5 on 2024-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0003_rename_ccy_id_country_ccy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market_data_source",
            name="function",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
