# Generated by Django 4.2.5 on 2024-04-16 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0004_market_data_source_function"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market_data_source",
            old_name="function",
            new_name="function_name",
        ),
    ]
