# Generated by Django 4.2.5 on 2024-04-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0005_rename_function_market_data_source_function_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
