# Generated by Django 4.2.5 on 2024-04-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0006_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="short_name",
            field=models.CharField(max_length=40),
        ),
    ]
