# Generated by Django 4.2.5 on 2024-08-17 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="msg_queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.BigIntegerField()),
                ("destination", models.CharField(max_length=50)),
                ("process", models.CharField(max_length=50)),
                ("routine", models.CharField(blank=True, max_length=100, null=True)),
                ("flag", models.CharField(max_length=1)),
                ("arg1", models.CharField(blank=True, max_length=100, null=True)),
                ("arg2", models.CharField(blank=True, max_length=100, null=True)),
                ("arg3", models.CharField(blank=True, max_length=100, null=True)),
                ("arg4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
