# Generated by Django 4.2.5 on 2024-03-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="identifier_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="instrument_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_type", models.CharField(max_length=25)),
                ("instrument_class", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=25, unique=True)),
                (
                    "identifier_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staticdata.identifier_type",
                    ),
                ),
                (
                    "instrument_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticdata.instrument_class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "instrument_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staticdata.instrument_class",
                    ),
                ),
            ],
        ),
    ]
