# Generated by Django 4.2.5 on 2024-03-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=25)),
                ("long_name", models.CharField(max_length=255)),
                (
                    "org_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.organization_type",
                    ),
                ),
                (
                    "owner_org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(max_length=35)),
                (
                    "base_ccy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.currency",
                    ),
                ),
                (
                    "domicile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.country",
                    ),
                ),
                (
                    "instrument_class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "issuer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_issuer",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "owner_org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_owner",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, unique=True)),
                (
                    "identifier_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.identifier_type",
                    ),
                ),
                (
                    "instrument_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "owner_or_ig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dividend_frequency", models.SmallIntegerField(default=4)),
                (
                    "instrument_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "sector_id",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.industry_sector",
                    ),
                ),
                (
                    "subsector_id",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.industry_subsector",
                    ),
                ),
            ],
        ),
    ]
