# Generated by Django 4.2.5 on 2024-04-28 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=25, unique=True)),
                ("long_name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "org_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.organization_type",
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(max_length=35, unique=True)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "base_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.currency",
                    ),
                ),
                (
                    "domicile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.country",
                    ),
                ),
                (
                    "instrument_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_issuer",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_owner",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, unique=True)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "identifier_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.identifier_type",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticdata.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dividend_frequency", models.SmallIntegerField(default=0)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.industry_sector",
                    ),
                ),
                (
                    "subsector",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.industry_subsector",
                    ),
                ),
            ],
        ),
    ]
