# Generated by Django 4.2.5 on 2024-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(max_length=25),
        ),
    ]
