# Generated by Django 4.2.5 on 2024-04-02 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staticdata", "0004_rename_owner_or_ig_identifier_owner_or_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identifier",
            old_name="owner_or_id",
            new_name="owner_org_id",
        ),
    ]
