# Generated by Django 4.2.5 on 2024-04-12 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staticdata", "0005_rename_owner_or_id_identifier_owner_org_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equity",
            old_name="instrument_id",
            new_name="instrument",
        ),
        migrations.RenameField(
            model_name="equity",
            old_name="sector_id",
            new_name="sector",
        ),
        migrations.RenameField(
            model_name="equity",
            old_name="subsector_id",
            new_name="subsector",
        ),
        migrations.RenameField(
            model_name="identifier",
            old_name="identifier_type_id",
            new_name="identifier_type",
        ),
        migrations.RenameField(
            model_name="identifier",
            old_name="instrument_id",
            new_name="instrument",
        ),
        migrations.RenameField(
            model_name="identifier",
            old_name="owner_org_id",
            new_name="owner_org",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="base_ccy_id",
            new_name="base_ccy",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="domicile_id",
            new_name="domicile",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="instrument_class_id",
            new_name="instrument_class",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="issuer_id",
            new_name="issuer",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="owner_org_id",
            new_name="owner_org",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="org_type_id",
            new_name="org_type",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="owner_org_id",
            new_name="owner_org",
        ),
    ]
