# Generated by Django 4.2.5 on 2024-04-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0005_rename_function_market_data_source_function_name"),
        ("staticdata", "0006_rename_instrument_id_equity_instrument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equity",
            name="sector",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="classifiers.industry_sector",
            ),
        ),
        migrations.AlterField(
            model_name="equity",
            name="subsector",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="classifiers.industry_subsector",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="short_name",
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="long_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
