'''
Django settings for howtoquant project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
'''

from pathlib import Path
from environ import Env
import itertools 

# Build paths inside the project like this: location = BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
location = BASE_DIR / 'howtoquant/.envs'
env.read_env(BASE_DIR /'howtoquant/.envs/.env_dev')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = env('ENVIRONMENT')
if ENVIRONMENT == 'development':
    DEBUG =True
    LOG_HANDLERS =['debug_handler', 'console_handler', 'error_handler']
else:
    DEBUG = False
    LOG_HANDLERS = ['info_handler']


ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # External
    'rest_framework',
    'corsheaders',
    # Internal
    'apps.accounting',
    'apps.classifiers',
    'apps.config',
    'apps.marketdata',
    'apps.staticdata',
    'apps.usermanagement',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'howtoquant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'howtoquant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'STORAGE_ENGINE': 'MyISAM / INNODB / ETC',
        'OPTIONS': {
            'init_command': 'SET foreign_key_checks = 0;',
        },
    }
}

# Logging configuration concept from:
# https://youtu.be/Z7BOBn8B5qA

# formatter configuration options can be found at:
# https://docs.python.org/3/library/logging.html#formatter-objects

FORMATTERS = {
    'basic': {
        'format': '{levelname} {asctime:s} {module} {filename} {lineno:d} {funcName} {message}',
        'style': '{',
    },
    'verbose': {
        'format': '{levelname} {asctime:s} {threadName} {thread:d} {module} {filename} {lineno:d} {name} {funcName} {process:d} {message}',
        'style': '{',
    },
}


HANDLERS = {
    'console_handler': {
        'class': 'logging.StreamHandler',
        'formatter': 'basic',
        'level': 'INFO',
    },
    'info_handler': {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'howtoquant/logs/info.log',
        'mode':'a',
        'level': 'INFO',
        'encoding': 'utf-8',
        'formatter': 'verbose',
        'backupCount': 1,
        'maxBytes': 1024 * 1024 * 5, # 5MB
    },
    'error_handler': {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'howtoquant/logs/error.log',
        'mode':'a',
        'level': 'WARNING',
        'encoding': 'utf-8',
        'formatter': 'verbose',
        'backupCount': 3,
        'maxBytes': 1024 * 1024 * 5, # 5MB
    },
    'debug_handler': {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'howtoquant/logs/debug.log',
        'level':'DEBUG',
        'mode':'a',
        'encoding': 'utf-8',
        'formatter': 'verbose',
        'backupCount': 3,
        'maxBytes': 1024 * 1024 * 5, # 5MB
    },
}

LOGGERS = {
    'django': {
        'handlers': LOG_HANDLERS,
        'level': 'DEBUG',
        'propagate': True,        
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': FORMATTERS,
    'handlers': HANDLERS,
    'loggers':LOGGERS
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Solution from https://www.youtube.com/watch?v=EzJdpp2l0bA
CORS_ALLOWED_ORIGINS = ['http://localhost:5173',]
# CORS_ORIGIN_ALLOW_ALL = True

POLYGON_API_KEY = env('POLYGON_API_KEY')

CRON_CLASSES = [
    'apps.config.services.flow_booker.FlowBooker',
    'apps.config.services.position_manager.PositionManager',
]
