# Generated by Django 5.0.8 on 2024-09-02 20:50

import apps.accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classifiers", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("staticdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="asset_flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("trade_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "settlement_date",
                    models.DateTimeField(default=apps.accounting.models.t_plus_two),
                ),
                ("quantity", models.FloatField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                ("source_id", models.PositiveBigIntegerField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_flow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_flow_flow_type",
                        to="classifiers.asset_flow_type",
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_flow_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "position_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_flow_position",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_flow_source",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="broker_account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cash_account", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "broker_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_broker",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "fund_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_fund",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "accounting_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifiers.accounting_method",
                    ),
                ),
                (
                    "base_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "fund_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_fund",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="book_default_account",
                        to="accounting.broker_account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cash_position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_position_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_position_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_position_ccy",
                        to="classifiers.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cash_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_ladder_cash_position",
                        to="accounting.cash_position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="instrument_position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_position_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_position_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_position_instrument",
                        to="staticdata.instrument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cash_position",
            name="instrument_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_position_instrument_position",
                to="accounting.instrument_position",
            ),
        ),
        migrations.CreateModel(
            name="asset_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_ladder_instrument_position",
                        to="accounting.instrument_position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="accrual_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("today_quantity", models.FloatField()),
                ("cumulative_quantity", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "accrual_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_ladder_accrual_type",
                        to="classifiers.accrual_type",
                    ),
                ),
                (
                    "instrument_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_ladder_instrument_position",
                        to="accounting.instrument_position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_owner",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instrument_position",
            name="strategy",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instrument_position_strategy",
                to="accounting.strategy",
            ),
        ),
        migrations.AddField(
            model_name="cash_position",
            name="strategy",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_position_strategy",
                to="accounting.strategy",
            ),
        ),
        migrations.CreateModel(
            name="trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trader_id", models.SmallIntegerField(default=2)),
                (
                    "trade_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("bs_indicator", models.CharField(max_length=2)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[apps.accounting.models.validate_greater_than_zero]
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "settlement_date",
                    models.DateTimeField(default=apps.accounting.models.t_plus_two),
                ),
                (
                    "trade_settlement_xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "gross_consideration",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "settlement_base_xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_account",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_instrument",
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "settlement_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_settlement_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_strategy",
                        to="accounting.strategy",
                    ),
                ),
                (
                    "trade_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_status",
                        to="classifiers.trade_status",
                    ),
                ),
            ],
        ),
    ]
