# Generated by Django 4.2.5 on 2024-05-19 20:39

import apps.accounting.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("staticdata", "0001_initial"),
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="accrual_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("today_quantity", models.FloatField()),
                ("cumulative_quantity", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="asset_flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("trade_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "settlement_date",
                    models.DateTimeField(default=apps.accounting.models.t_plus_two),
                ),
                ("quantity", models.FloatField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="asset_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="broker_account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cash_account", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cash_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cash_position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fifo_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="instrument_position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_owner",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="weighted_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighted_pnl_asset_ladder",
                        to="accounting.asset_ladder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trader_id", models.SmallIntegerField(default=2)),
                (
                    "trade_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("bs_indicator", models.CharField(max_length=2)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[apps.accounting.models.validate_greater_than_zero]
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "settlement_date",
                    models.DateTimeField(default=apps.accounting.models.t_plus_two),
                ),
                (
                    "trade_instrument_xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "trade_setlement_xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "gross_consideration",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "settlement_base_xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_account",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_instrument",
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "settlement_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_settlement_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_strategy",
                        to="accounting.strategy",
                    ),
                ),
                (
                    "trade_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_status",
                        to="classifiers.trade_status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="position_snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                ("ladder_id", models.PositiveBigIntegerField()),
                ("weighted_average_cost", models.FloatField()),
                ("weighted_lifetime_total_pnl", models.FloatField()),
                ("weighted_lifetime_instrument_pnl", models.FloatField()),
                ("weighted_lifetime_fx_pnl", models.FloatField()),
                ("weighted_ytd_total_pnl", models.FloatField()),
                ("weighted_ytd_instrument_pnl", models.FloatField()),
                ("weighted_ytd_fx_pnl", models.FloatField()),
                ("weighted_mtd_total_pnl", models.FloatField()),
                ("weighted_mtd_instrument_pnl", models.FloatField()),
                ("weighted_mtd_fx_pnl", models.FloatField()),
                ("weighted_daily_total_pnl", models.FloatField()),
                ("weighted_daily_instrument_pnl", models.FloatField()),
                ("weighted_daily_fx_pnl", models.FloatField()),
                ("fifo_average_cost", models.FloatField()),
                ("fifo_lifetime_total_pnl", models.FloatField()),
                ("fifo_lifetime_instrument_pnl", models.FloatField()),
                ("fifo_lifetime_fx_pnl", models.FloatField()),
                ("fifo_ytd_total_pnl", models.FloatField()),
                ("fifo_ytd_instrument_pnl", models.FloatField()),
                ("fifo_ytd_fx_pnl", models.FloatField()),
                ("fifo_mtd_total_pnl", models.FloatField()),
                ("fifo_mtd_instrument_pnl", models.FloatField()),
                ("fifo_mtd_fx_pnl", models.FloatField()),
                ("fifo_daily_total_pnl", models.FloatField()),
                ("fifo_daily_instrument_pnl", models.FloatField()),
                ("fifo_daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source_ladder",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
