# Generated by Django 5.0.8 on 2024-09-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        (
            "marketdata",
            "0002_value_scheme_pref_value_scheme_order_value_scheme_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset_ladder",
            name="value_scheme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asset_ladder_value_scheme",
                to="marketdata.value_scheme",
            ),
            preserve_default=False,
        ),
    ]
