# Generated by Django 5.0.8 on 2024-09-02 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_asset_ladder_value_scheme"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("marketdata", "0003_value_scheme_ladder_value_scheme_order_ladder"),
    ]

    operations = [
        migrations.CreateModel(
            name="fifo_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fifo_pnl_asset_ladder",
                        to="accounting.asset_ladder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="position_snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                ("ladder_id", models.PositiveBigIntegerField()),
                ("weighted_average_cost", models.FloatField()),
                ("weighted_lifetime_total_pnl", models.FloatField()),
                ("weighted_lifetime_instrument_pnl", models.FloatField()),
                ("weighted_lifetime_fx_pnl", models.FloatField()),
                ("weighted_ytd_total_pnl", models.FloatField()),
                ("weighted_ytd_instrument_pnl", models.FloatField()),
                ("weighted_ytd_fx_pnl", models.FloatField()),
                ("weighted_mtd_total_pnl", models.FloatField()),
                ("weighted_mtd_instrument_pnl", models.FloatField()),
                ("weighted_mtd_fx_pnl", models.FloatField()),
                ("weighted_daily_total_pnl", models.FloatField()),
                ("weighted_daily_instrument_pnl", models.FloatField()),
                ("weighted_daily_fx_pnl", models.FloatField()),
                ("fifo_average_cost", models.FloatField()),
                ("fifo_lifetime_total_pnl", models.FloatField()),
                ("fifo_lifetime_instrument_pnl", models.FloatField()),
                ("fifo_lifetime_fx_pnl", models.FloatField()),
                ("fifo_ytd_total_pnl", models.FloatField()),
                ("fifo_ytd_instrument_pnl", models.FloatField()),
                ("fifo_ytd_fx_pnl", models.FloatField()),
                ("fifo_mtd_total_pnl", models.FloatField()),
                ("fifo_mtd_instrument_pnl", models.FloatField()),
                ("fifo_mtd_fx_pnl", models.FloatField()),
                ("fifo_daily_total_pnl", models.FloatField()),
                ("fifo_daily_instrument_pnl", models.FloatField()),
                ("fifo_daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source_ladder",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "value_scheme_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_snapshot_value_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="weighted_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighted_pnl_asset_ladder",
                        to="accounting.asset_ladder",
                    ),
                ),
            ],
        ),
    ]
