# Generated by Django 4.2.5 on 2024-05-05 16:09

import apps.accounting.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0003_rename_acrrual_type_accrual_type"),
        (
            "marketdata",
            "0002_value_scheme_value_scheme_pref_value_scheme_rule_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounting", "0002_trade_instrument_position_cash_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="asset_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_ladder_instrument_position",
                        to="accounting.instrument_position",
                    ),
                ),
                (
                    "value_scheme_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_ladder_value_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="weighted_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighted_pnl_asset_ladder",
                        to="accounting.asset_ladder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="position_snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("market_value", models.FloatField()),
                ("market_price", models.FloatField()),
                ("ladder_id", models.PositiveBigIntegerField()),
                ("weighted_average_cost", models.FloatField()),
                ("weighted_lifetime_total_pnl", models.FloatField()),
                ("weighted_lifetime_instrument_pnl", models.FloatField()),
                ("weighted_lifetime_fx_pnl", models.FloatField()),
                ("weighted_ytd_total_pnl", models.FloatField()),
                ("weighted_ytd_instrument_pnl", models.FloatField()),
                ("weighted_ytd_fx_pnl", models.FloatField()),
                ("weighted_mtd_total_pnl", models.FloatField()),
                ("weighted_mtd_instrument_pnl", models.FloatField()),
                ("weighted_mtd_fx_pnl", models.FloatField()),
                ("weighted_daily_total_pnl", models.FloatField()),
                ("weighted_daily_instrument_pnl", models.FloatField()),
                ("weighted_daily_fx_pnl", models.FloatField()),
                ("fifo_average_cost", models.FloatField()),
                ("fifo_lifetime_total_pnl", models.FloatField()),
                ("fifo_lifetime_instrument_pnl", models.FloatField()),
                ("fifo_lifetime_fx_pnl", models.FloatField()),
                ("fifo_ytd_total_pnl", models.FloatField()),
                ("fifo_ytd_instrument_pnl", models.FloatField()),
                ("fifo_ytd_fx_pnl", models.FloatField()),
                ("fifo_mtd_total_pnl", models.FloatField()),
                ("fifo_mtd_instrument_pnl", models.FloatField()),
                ("fifo_mtd_fx_pnl", models.FloatField()),
                ("fifo_daily_total_pnl", models.FloatField()),
                ("fifo_daily_instrument_pnl", models.FloatField()),
                ("fifo_daily_fx_pnl", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_snapshot_source_ladder",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "value_scheme_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_snapshot_value_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fifo_pnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_cost", models.FloatField()),
                ("lifetime_total_pnl", models.FloatField()),
                ("lifetime_instrument_pnl", models.FloatField()),
                ("lifetime_fx_pnl", models.FloatField()),
                ("ytd_total_pnl", models.FloatField()),
                ("ytd_instrument_pnl", models.FloatField()),
                ("ytd_fx_pnl", models.FloatField()),
                ("mtd_total_pnl", models.FloatField()),
                ("mtd_instrument_pnl", models.FloatField()),
                ("mtd_fx_pnl", models.FloatField()),
                ("daily_total_pnl", models.FloatField()),
                ("daily_instrument_pnl", models.FloatField()),
                ("daily_fx_pnl", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fifo_pnl_asset_ladder",
                        to="accounting.asset_ladder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cash_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_ladder_cash_position",
                        to="accounting.cash_position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="asset_flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_id", models.PositiveBigIntegerField()),
                ("trade_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "settlement_date",
                    models.DateTimeField(default=apps.accounting.models.t_plus_two),
                ),
                ("quantity", models.FloatField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "xrate",
                    models.FloatField(
                        default=1,
                        validators=[apps.accounting.models.validate_greater_than_zero],
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "asset_flow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_flow_flow_type",
                        to="classifiers.asset_flow_type",
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_flow_ccy",
                        to="classifiers.currency",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="accrual_ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("today_quantity", models.FloatField()),
                ("cumulative_quantity", models.FloatField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "accrual_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_ladder_accrual_type",
                        to="classifiers.accrual_type",
                    ),
                ),
                (
                    "instrument_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_ladder_instrument_position",
                        to="accounting.instrument_position",
                    ),
                ),
            ],
        ),
    ]
