# Generated by Django 4.2.5 on 2024-08-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_trade_setlement_xrate_trade_trade_settlement_xrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_position',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='instrument_position',
            name='position_type',
        ),
    ]
