# Generated by Django 4.2.5 on 2024-08-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounting", "0005_remove_cash_position_position_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset_flow",
            name="source",
        ),
        migrations.AddField(
            model_name="asset_flow",
            name="position_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_flow_position",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset_flow",
            name="source_id",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset_flow",
            name="source_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_flow_source",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
    ]
