# Generated by Django 4.2.5 on 2024-08-30 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0006_remove_asset_flow_source_asset_flow_position_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset_ladder",
            old_name="value_scheme_id",
            new_name="value_scheme",
        ),
    ]
