# Generated by Django 5.0.8 on 2024-08-31 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0007_rename_value_scheme_id_asset_ladder_value_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accrual_ladder",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="asset_ladder",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cash_ladder",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
