# Generated by Django 4.2.5 on 2024-08-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="value_scheme_order",
            name="value_field",
        ),
        migrations.RemoveField(
            model_name="value_scheme_order",
            name="value_scheme",
        ),
        migrations.AddField(
            model_name="value_scheme",
            name="value_scheme_order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="value_scheme_value_scheme_order",
                to="marketdata.value_scheme_order",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="value_scheme_order",
            name="ladder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="value_scheme_order",
            name="value_spec",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="value_scheme_order_value_spec",
                to="marketdata.value_spec",
            ),
            preserve_default=False,
        ),
    ]
