# Generated by Django 4.2.5 on 2024-04-13 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="download_data",
            name="owner_org",
        ),
    ]
