# Generated by Django 4.2.5 on 2024-05-05 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0002_accounting_method_acrrual_type_asset_flow_type_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("staticdata", "0001_initial"),
        ("accounting", "0001_initial"),
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="value_scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_ladder",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_owner",
                        to="staticdata.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme_pref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100, unique=True)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "effective_date_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "effective_date_to",
                    models.DateTimeField(default=datetime.date(9999, 12, 31)),
                ),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_instrument",
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "instrument_class_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_rule_instrument_class",
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "instrument_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_rule_instrument_type",
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "value_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_value_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.SmallIntegerField()),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "value_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_schme_order_value_field",
                        to="marketdata.value_field",
                    ),
                ),
                (
                    "value_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_order_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="value_scheme",
            name="value_scheme_pref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="value_scheme_value_scheme_pref",
                to="marketdata.value_scheme_pref",
            ),
        ),
    ]
