# Generated by Django 5.0.8 on 2024-09-02 20:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("classifiers", "0001_initial"),
        ("marketdata", "0001_initial"),
        ("staticdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="value_scheme_pref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100, unique=True)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.SmallIntegerField()),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "value_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_order_value_spec",
                        to="marketdata.value_spec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_owner",
                        to="staticdata.organization",
                    ),
                ),
                (
                    "value_scheme_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_value_scheme_order",
                        to="marketdata.value_scheme_order",
                    ),
                ),
                (
                    "value_scheme_pref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_value_scheme_pref",
                        to="marketdata.value_scheme_pref",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="value_scheme_rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "effective_date_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "effective_date_to",
                    models.DateTimeField(default=datetime.date(9999, 12, 31)),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_account",
                        to="accounting.broker_account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_book",
                        to="accounting.book",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_instrument",
                        to="staticdata.instrument",
                    ),
                ),
                (
                    "instrument_class_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_rule_instrument_class",
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "instrument_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_scheme_rule_instrument_type",
                        to="classifiers.instrument_class",
                    ),
                ),
                (
                    "value_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_scheme_rule_value_scheme",
                        to="marketdata.value_scheme",
                    ),
                ),
            ],
        ),
    ]
