# Generated by Django 4.2.5 on 2024-08-29 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketdata", "0002_remove_value_scheme_order_value_field_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="value_scheme_order",
            old_name="order",
            new_name="ordering",
        ),
    ]
