# Generated by Django 5.0.8 on 2024-09-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "marketdata",
            "0002_value_scheme_pref_value_scheme_order_value_scheme_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="value_scheme",
            name="ladder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="value_scheme_ladder",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="value_scheme_order",
            name="ladder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
    ]
